---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-api-config
  namespace: hello-api
spec:
  encryptedData:
    DB_PASSWORD: AgBWJk+tKoQCGHVC3UIbSXKQaXRJHk980V+hdS8fp4B7fOo1YH9TXt4S4zKP1a1W4gw2De6G9nHmnOjHgCPLmKoCxf8CKer4G3F/fTerSbaSP+CqZ0e6brq5/zPVt/oVMvTlcnIyH4juVdGiX1xzzBrkOxg+ONk8HJexH/CymtkUwt5Ucwnzmrq10oF+6Xc5+XTz2EZPGvXA3EkW5VbcNFGOtaAJYBzRDPnE2wKiqQm2XgQl5POA3T1VczDN2E4UJVaO7zkZvla4q89tRtlr0opB6nYtPzAYtvhEUdUr6Jgsxx1bCY+rCOeChoAkgj+n9Wos3oS3ej/TzzgC01AowMp+ggEXDIKljWWHO0Qz1pD9eiSpbRUQFXViFUAGodJCnmWRfdSldEVKZJHqbfbTxQ34bMOU5G/vJuXzaT08e/xSB44rG3NPbBH6WdIgH0gMWmo3ZlGR3jQoOh3qOg30eniixfjd7JVSjkljtajkM6EljIRVTZplMtso/+0DeVMaOZAMlpNlzFj2lhmmKF+QOujPa4OEeAjV1HamOTnVWBqGLwS5btE9kXJxQWW+jipdYpG1M+6cZuY9rTj+Rjh+gA/eKRPH8VOUSkDsIDM8akZRbTphMXmf4SIJxR2/jau2OppZ6XlW9fb9bmPNmBrwZZvHJp79GHmWbG4AfUN/SrkapgXFT7GnV2u+rHhPjZ2VRs9+e0p3TF9afMQNhoceDio=
  template:
    metadata:
      creationTimestamp: null
      name: hello-api-config
      namespace: hello-api
