---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-api-config
  namespace: hello-api
spec:
  encryptedData:
    DB_PASSWORD: AgBcQMWfR0G8+sFklU/gW369dB8NyR8UQItkfHqrefcRKFnnmtRVP5CmJZju668SuHbRu62B34d79nVDCvBU7rMEUWsNZwCWyPwNsEo0skN+Su1WcXfbNGHCf4gd6D7J767sMbmAXlHid5cL5g1kSAs5hxmt2Fga9X1IYw+w9jTS7+hKkxFnA238o40xhcv8qc1xIW0VVZPWU71co1MS4rboskwWqSObeMJKCuEeJUwWJnRIozc2RPKuQ9wb1uQUEFC7cRQZg+Y5RJwWTZaZe4zVQyM4IxixPNcIFHMRzdwUXQFg2/gtwfS4qqFF+n290uhmMq7zy4W62Wu0IyNiMdB0AH4KLuhMiRuuQbRpIStKfPWKxkxuyhEc9oRJL1v1NDkzKizXu2w5dh2xCUytAApM2Xby+reSOnn8B/ELA0jgbvd+aYsbeiFB4jnK0VTO45oerOPPBlFCKwLgTCZm1DmI4T0krU9670i7IaQdNtizmnNozSB+HdKhqTSQvlPWJRWw1tDRpNrJrVQukbTpuLArdwDsvdj/U36TCFUoheRL9V7kD1TIriPOxDfz0Ivr50zYpmASiH1G1GF7/2E1uxfsGUrniurvgpdBk5gZsyLJdWIpkqCK3L4dLC3zrFH7Suc9xc9j8Etm+afWCfySzkFhv3mLRoA4FdcUbnwCrvwp0K4PJGej/GN15Lk6UyBTbQkrPt4u3qEbtia/myndesI=
  template:
    metadata:
      creationTimestamp: null
      name: hello-api-config
      namespace: hello-api
