apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: platform               # or “default” if you skipped the AppProject
  source:
    repoURL: https://stefanprodan.github.io/podinfo   # Helm repo URL
    chart: podinfo                                    # <── Helm field, not path
    targetRevision: 6.8.0                             # lock chart version
    helm:
      values: |-
        replicaCount: 1
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: podinfo.localhost
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
