apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-a
  namespace: argocd
spec:
  description: Team A application
  sourceRepos:
    - https://github.com/tylermac92/gitops-platform
  destinations:
    - namespace: team-a
      server: https://kubernetes.default.svc
