image:
  repository: ghcr.io/tylermac92/hello-api
  tag: "2e8d9893a2da13009662b2104d088b80cdf478c6"
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: hello-api.localhost
      paths:
        - path: /
          pathType: Prefix
