image:
  repository: ghcr.io/tylermac92/hello-api
  tag: "4c4ad5890eb6d61e40de1613a5344f6f1f7e183e"
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: hello-api.localhost
      paths:
        - path: /
          pathType: Prefix
