image:
  repository: ghcr.io/tylermac92/hello-api
  tag: "cadc97a959cb63d95e6d5621d1d5e6a89efe63a1"
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: hello-api.localhost
      paths:
        - path: /
          pathType: Prefix
