apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-rollouts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rollouts-controller
  namespaceSelector:
    matchNames:
      - argo-rollouts
    endpoints:
      - port: metrics
        interval: 30s
